// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aairos.Data;

#nullable disable

namespace aairos.Migrations
{
    [DbContext(typeof(devicedetailsContext))]
    partial class devicedetailsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("aairos.Model.devicedetails", b =>
                {
                    b.Property<int>("DeviceDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeviceDetailsID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceDetailsGUID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<int>("ProfileID")
                        .HasColumnType("int");

                    b.Property<int?>("Sensor1")
                        .HasColumnType("int");

                    b.Property<int?>("Sensor2")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ValveID")
                        .HasColumnType("int");

                    b.Property<int?>("ValveStatus")
                        .HasColumnType("int");

                    b.HasKey("DeviceDetailsID");

                    b.ToTable("devicedetail");
                });
#pragma warning restore 612, 618
        }
    }
}
